### ISSUE TITLE
How to disable prefetch?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#10]
The default behavior of prefetch is causing a ton of overhead when the page has many links.

I really want to prefetch only the links that have high probability of being clicked (which is not something that a framework should try to infer unless by using proximity).

The only way I found to disable the default behavior is to override the Link component and restrict direct imports from `next/link`.

https://github.com/gajus/gajus-com/blob/b70e27a099dfa3210986419b0da96825f03e2eab/src/components/Link.tsx#L4-L11

https://github.com/gajus/gajus-com/blob/1e9770c66a9d65a437439dd2d94572401fdb254e/.eslintrc.json#L35-L38

**Comment by leerob** [comment]
This is the pattern I usually recommend 👍  We still think the default is correct for prefetching, but since components can easily be extended and composed based on your specific requirements, this pattern allows you to lock things down further.

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
