### ISSUE TITLE
How to inject configuration at runtime?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#11]
I am unable to find documentation for how to inject variables into Next.js at runtime.

For context, we don't inline configuration values into our builds. Instead, we define a global variable (such as `window.CWA` in case of https://contra.com/gajus) which we populate with values at runtime. This pattern allows to adjust configurations of deployments without needing to rebuild them. 

It appears that this feature used to exist, but can longer be used with app/ router and RSC.

https://nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration

**Comment by leerob** [comment]
We recently updated our docs around this for "runtime environment variables" when [self-hosting](https://nextjs.org/docs/app/building-your-application/deploying#environment-variables). It's a similar idea on Vercel, except you can read from [Edge Config](https://vercel.com/docs/storage/edge-config) to get your runtime values.

We recommend this approach over using the deprecated runtime configuration.

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
