### ISSUE TITLE
How to override the cache-control headers for dynamic pages?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#12]
Just realized that production app route pages are being served with:

```
cache-control: private, no-cache, no-store, max-age=0, must-revalidate
```

There appears to be no way to override `cache-control` headers.

This would be problematic since it means we cannot leverage our CDN to cache those pages at the edge.

Related thread:

https://github.com/vercel/next.js/issues/22319#issuecomment-1565268095

**Comment by fgnass** [comment]
I just noticed the same as Lighthouse reports the following issue for all dynamic pages:

> Page prevented back/forward cache restoration
> Pages whose main resource has `cache-control:no-store` cannot enter back/forward cache.

I did manage to overwrite the `cache-control` header in `next.config.js` but this feels wrong. Also [the docs say](https://nextjs.org/docs/app/api-reference/next-config-js/headers#cache-control) that this should not be possible. I have the feeling that I am missing something obvious here, I can't believe that this is the intended behaviour.

**Comment by leerob** [comment]
Dynamically rendered pages set a `Cache-Control` header of `private, no-cache, no-store, max-age=0, must-revalidate` to prevent user-specific data from being cached. This applies to both the App Router and Pages Router. This also includes Draft Mode.

Should this page be statically rendered instead? Or use ISR?

**Comment by leerob** [comment]
Note that you can still cache _data_, for example setting headers of `getServerSideProps`, or on specific data fetches in the App Router.

**Comment by yhakbar** [comment]
@leerob , as it pertains to this comment here: https://github.com/vercel/next.js/issues/22319#issuecomment-1741395007

Do you know why it is that this functionality isn't exposed as an opt-in configuration in the app router for dynamic pages?

There are business use-cases that benefit from being able to explicitly set `Cache-Control` headers to desired values, even when the pages are dynamically generated on-the-fly.

While there _might_ be a workable solution that has the page statically rendered or statically rendered with ISR, and that solution might be more efficient than just setting the `Cache-Control` header to a desired value explicitly for a dynamically rendered page, why remove that flexibility?

ISR doesn't allow for dynamically updated dynamic routes, as far as I know, and it seems like the only alternative to having the ability to explicitly set `Cache-Control` for situations like this is to either do some complicated logic with middleware, or use a reverse proxy to inject the desired `Cache-Control` headers after the response leaves NextJS.

**Comment by leerob** [comment]
If you're using NGINX per that comment, that you probably are looking a static page you can set caching headers for the entire page. https://nextjs.org/docs/app/building-your-application/deploying/static-exports

**Comment by gajus** [comment]
For context, our use case is that we have dynamic pages that we are Okay with being cached, i.e. the contents of the pages is not impacted by the user session, but rather by the data in the database and temporarily showing slate data does not negatively impact user experience.

**Comment by yhakbar** [comment]
> If you're using NGINX per that comment, that you probably are looking a static page you can set caching headers for the entire page. https://nextjs.org/docs/app/building-your-application/deploying/static-exports

No, I'm still trying to have pages rendered dynamically by NGINX, I just want the `Cache-Control` header in the response to be a value I desire, and running the response through a reverse proxy is a way to do that despite NGINX not allowing explicitly defining response `Cache-Control` header values in responses when using the app router.

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
