### ISSUE TITLE
Next.js does not support NodeNext module resolution

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#14]
https://github.com/vercel/next.js/issues/46078

This is a fairly major issue since every other workspace in our repository uses NodeNext module resolution.

The current proposed solution by the community is to switch to using `bundler`, but that's is a different module loading strategy that does not achieve the same results that `NodeNext` does – namely the ability to define and restrict module exports using `exports` in `package.json`.

**Comment by leerob** [comment]
Heard, yeah this is an opportunity for improvement.

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
