### ISSUE TITLE
How do I wait for GitHub checks to pass before attempting to deploy to Vercel?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#2]
I could not figure out how to delay Vercel deployment until after all checks have passed.

I think it can be achieved by disabling their GitHub integration and just issuing the deploy hooks manually.

I wish there was a built-in way to just wait for all checks to pass.

**Comment by leerob** [comment]
Heard! We want to add something built-in for this. Right now, you are correct you would remove the git integration and instead use the CLI in your own Action or CI check.

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
