### ISSUE TITLE
How to add favicon.png?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#5]
This is more documentation than anything else, but it threw me off that I could not find how to add `favicon.png`.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons

This document mentions multiple icon formats that are added using file name conventions, but does nothing to say how to add a custom favicon.

I ended up just defining `icons` in metadata.

https://github.com/gajus/gajus-com/blob/f2510c64604d16f25a984a9908b6088e2f52fef0/src/app/layout.tsx#L12-L18

I think Next.js should be updated to handle non `.ico` favicon formats and/or include a section in the linked documentation for how to add custom icons mentioning keywords like `png` and `gif`.

**Comment by leerob** [comment]
The file system metadata only supports `.ico`: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#image-files-ico-jpg-png

But as you ended up with, this is the solution if you need anything other that than. Use the config-based metadata, and place your favicon wherever you'd prefer.

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
