### ISSUE TITLE
How to get client's IP address?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#8]
It appears that the only way to do it is by interpreting the request headers.

https://github.com/gajus/gajus-com/blob/f2510c64604d16f25a984a9908b6088e2f52fef0/src/routines/getClientIpAddress.ts

This is mostly fine as far as I can think of, but the lack of [documentation](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fnextjs.org%2Fdocs%2Fapp%2F+client+ip+address) left me scavenging across the Internet for possible solutions.

A section in the documentation about `next/headers` mentioning common use cases would be sufficient.

**Comment by leerob** [comment]
Good call, updated here: https://github.com/vercel/next.js/issues/47793#issuecomment-1859249626

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
