### ISSUE TITLE
How to load data once?

### ISSUE THREAD

**Issue by gajus** [gajus/gajus-com#9]
It looks like the [documentation](https://nextjs.org/docs/app/building-your-application/data-fetching/patterns) about data fetching patterns has been updated since, but the major question I had was _how do I load data only once when querying the database?_

If my understanding is correct, the short answer is to use [`cache`](https://react.dev/reference/react/cache).

That's what I did here:

https://github.com/gajus/gajus-com/commit/bf3a02056f4390437de8eb1c093bf509cca774ad

My gripe with this approach is that it conflates separate concepts of cache and loading data once.

Using this example:

```ts
export const generateMetadata = async ({
  params: { blogPostSlug },
}: Props): Promise<Metadata> => {
  const blogPostHead = await findBlogPostHead(blogPostSlug);

  // ...
};

export default async ({ params: { blogPostSlug } }: Props) => {
  const blogPostHead = await findBlogPostHead(blogPostSlug);

  // ...
};
```

I understand that as long as `findBlogPostHead` (or in our case its parent function) is wrapped in `cache`, then the resources are only going to be fetched once within the same request.

However, aside from this making the code less re-usable (you can no longer use `findBlogPostHead` outside of Next.js), this introduces indirection that allows easy/accidental introduction of bugs (someone couldn't use `findBlogPostHead` in their script so they removed `cache()` from the parent function).

As an end user, what I really want is simply a method to preload data once for both methods (or get rid of the separation between `generateMetadata` and the main route), i.e.

```ts
const load = ({
  params: { blogPostSlug },
}: Props) => {
  return await findBlogPostHead(blogPostSlug);
};

export const generateMetadata = async ({
  data: blogPostHead,
}): Promise<Metadata> => {
  const blogPostHead = await findBlogPostHead(blogPostSlug);

  // ...
};

export default async ({
  data: blogPostHead,
}) => {
  const blogPostHead = await findBlogPostHead(blogPostSlug);

  // ...
};
```

I also like the data [loader pattern](https://remix.run/docs/en/main/guides/data-loading) that Remix implement (albeit it does not work with RSC).

**Comment by leerob** [comment]
- The data loader pattern mentioned [can be achieved in Next.js](https://nextjs.org/docs/app/building-your-application/data-fetching/patterns#preloading-data) (it's what the Pages Router does, effectively). 
- `generateMetadata` needs to be separate from page rendering to support streaming.
- We're working on improving the DX of caching further, where it's easier to switch between the cached & uncached "boundaries". 

> you can no longer use `findBlogPostHead` outside of Next.js

If the core logic of this function needs to be reused in multiple places, that bit could be lifted outside of Next.js (to some shared package) and then the "data layer" in Next.js handles the caching / revalidating of data from the upstream. We recommend this pattern especially with Server Actions.

https://nextjs.org/blog/security-nextjs-server-components-actions

**Comment by gajus** [comment]
Closing. Originally opened this issue to share feedback with Vercel team. This no longer serves purpose.
